object Versions {
    const val lifecycle = "2.6.1"
    const val navigation = "2.5.3"
    const val coil = "2.2.2"
    const val timber = "5.0.1"
    const val kotlin = "1.10.0"
    const val compose = "1.4.2"
    const val composeActivity = "1.7.1"
    const val composePaging = "1.0.0-alpha18"
    const val daggerHilt = "2.45"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigation = "1.1.0-alpha01"
    const val room = "2.5.0"
    const val coroutines = "1.6.4"
    const val retrofit = "2.9.0"
    const val kotlinSerialization = "1.4.1"
    const val kotlinSerializationConverter = "0.8.0"
    const val firebase = "31.2.2"
    // testing
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.5"
    const val espresso = "3.5.1"
}